export const WINDOW = {
  SET_ACTIVE_WINDOW: 'cn/Window/SET_ACTIVE_WINDOW',
  SET_EXPERIENCE_WINDOW_VISIBILITY:
    'cn/Window/SET_EXPERIENCE_WINDOW_VISIBILITY',
  SET_EXPERIENCE_WINDOW_MINIMIZE: 'cn/Window/SET_EXPERIENCE_WINDOW_MINIMIZE',
  SET_EDUCATION_WINDOW_VISIBILITY: 'cn/Window/SET_EDUCATION_WINDOW_VISIBILITY',
  SET_EDUCATION_WINDOW_MINIMIZE: 'cn/Window/SET_EDUCATION_WINDOW_MINIMIZE',
  SET_ABOUT_ME_WINDOW_VISIBILITY: 'cn/Window/SET_ABOUT_ME_WINDOW_VISIBILITY',
  SET_ABOUT_ME_WINDOW_MINIMIZE: 'cn/Window/SET_ABOUT_ME_WINDOW_MINIMIZE',
  SET_LINKS_WINDOW_VISIBILITY: 'cn/Window/SET_LINKS_WINDOW_VISIBILITY',
  SET_LINKS_WINDOW_MINIMIZE: 'cn/Window/SET_LINKS_WINDOW_MINIMIZE',
  SET_SHUTDOWN_POPUP_VISIBILITY: 'cn/Window/SET_SHUTDOWN_POPUP_VISIBILITY',
  MINIMIZE_ALL_EXCEPT: 'cn/Window/MINIMIZE_ALL_EXCEPT',
};
